# Site settings
title: XiaoSheng Blog
SEOTitle: 王晓圣的博客 | XiaoSheng Blog
header-img: img/home-bg.jpg
email: xiaoshengmr@163.com
description: "关于分布式计算引擎、大规模个性化推荐实时机器学习 | 王晓圣，Flink & Distributing Process，Software Engineer | 这里是 @XiaoSheng 王晓圣 的个人博客，与你一起发现更大的世界。"
keyword: "XiaoSheng, XiaoSheng Blog, 王晓圣的博客, xiaoshengWang, 王晓圣, iOS, Apple, iPhone"
url: "https://github.com/xiaoshengMr"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "http://xiaoshengmr.github.io/" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "王晓圣,大规模个性化推荐深度学习系统架构"
sidebar-avatar: /img/avatar_xs.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
zhihu_username:     xiaoshengMr
github_username:    xiaoshengMr




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: f2c84e7629bb1446c1a4                            #生成的clientID
  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
  repo: qiubaiying.github.io    #仓库名称
  owner: qiubaiying    #github用户名
  admin: qiubaiying
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "知乎·王晓圣",
        href: "https://www.zhihu.com/people/xiao-sheng-76-68-52/"
    }
]
